import work


output,error = work.run('test.py','testinput')
print(output)
print(error)